language: java
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.m2
jdk:
- oraclejdk8
before_install: eval "$(ssh-agent -s)"
install: bash src/main/bash/dependencies.sh
script: bash src/main/bash/run.sh